services:
  mysql-master:
    image: mysql:8
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogdb
    ports:
      - "3307:3306"
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  mysql-slave1:
    image: mysql:8
    container_name: mysql-slave1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogdb 
    ports:
      - "3308:3306"
    depends_on:
      - mysql-master
    command: >
      --server-id=2
      --relay-log=relay-bin
      --read-only=1
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  mysql-slave2:
    image: mysql:8
    container_name: mysql-slave2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogdb 
    ports:
      - "3309:3306"
    depends_on:
      - mysql-master
    command: >
      --server-id=3
      --relay-log=relay-bin
      --read-only=1
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  node-app:
    build: .
    container_name: node-app
    restart: always
    depends_on:
      mysql-master:
        condition: service_healthy
      mysql-slave1:
        condition: service_healthy
      mysql-slave2:
        condition: service_healthy
    ports:
      - "5000:5000"
    command: nodemon server.js       # ðŸ‘ˆ Auto-reload on file change
    volumes:
      - .:/app                       # ðŸ‘ˆ Mount local folder
      - /app/node_modules            # ðŸ‘ˆ Prevent host node_modules override
